### ISSUE TITLE
Submenu

### ISSUE THREAD

**Issue by mitchrobfilms** [bryanbrazil/skin.mimic#16]
Hi how can I get the sub menus to work every time I close kodi it deleted the sub menu how can I get them to stay thanks

**Comment by bryanbrazil** [comment]
Sounds like a script.skinshortcuts issue. Make sure you have the following file in the skin's 1080i folder and it is being updated with your menu changes. 

script-skinshortcuts-includes.xml

**Comment by bryanbrazil** [comment]
Submenus have been overhauled to comply with the new data format.
