### ISSUE TITLE
.shortcuts will soon be deprecated

### ISSUE THREAD

**Issue by Ignoble61** [bryanbrazil/skin.mimic#17]
From a quick (very quick!) check of the repo, this is the only skin other than Nox5 (+ non repo variants) than will be affected by an upcoming change to the skin shortcuts script.

Support for the very old .shortcuts files are soon to removed, with only support for the .DATA.xml files for providing defaults for menu's/submenus - please migrate to the new file format ASAP :)

(Relevant PR - https://github.com/BigNoid/script.skinshortcuts/pull/30 - if you use the same default submenus as Nox5, you can just use the .DATA.xml files that Nox5 now uses.)

Any questions, please ask :)

**Comment by bryanbrazil** [comment]
Thanks for pointing this out, will update right away!

**Comment by bryanbrazil** [comment]
Fixed, thanks.
