### ISSUE TITLE
Not reading settings.xml from userdata

### ISSUE THREAD

**Issue by billymcintosh** [bryanbrazil/skin.mimic#22]
Turned on Kodi which them updated Mimic theme. Now the theme doesn't appear to read ```.kodi/userdata/addon_data/skin.mimic/settings.xml``` and all my settings have gone. 

Using Jarvis on Android TV.

**Comment by bryanbrazil** [comment]
The entire menu/widget/background system was overhauled in Mimic 3.1.0.
Please see the support thread on the Kodi forum.

http://forum.kodi.tv/showthread.php?tid=237267

Turned on Kodi which them updated Mimic theme. Now the theme doesn't appear
to read .kodi/userdata/addon_data/skin.mimic/settings.xml and all my
settings have gone.

Using Jarvis on Android TV.

—
Reply to this email directly or view it on GitHub
<https://github.com/bryanbrazil/skin.mimic/issues/22>.

**Comment by billymcintosh** [comment]
Cheers.   Great work on the skin.
