### ISSUE TITLE
Remove Logo View Background

### ISSUE THREAD

**Issue by manuel-hegner** [bryanbrazil/skin.mimic#23]
Hey,

I really love your skin. It has nearly everything I want. I would only like to request an enhancement for the "Logo" view. At the moment it does not look very nice because the default background darkens the fanart so much. It would look better without a background.

I tried to change the background color in the settings but then everything else looks kind of weird and in the "Logo" view the top bar is not visible enough. 

ps: maybe add the watched/in progress indicator to this view?

**Comment by bryanbrazil** [comment]
I likely won't be making any changes to this view, though you're welcome to post a mod in the Mimic forum.

http://forum.kodi.tv/forumdisplay.php?fid=218
