### ISSUE TITLE
Watched status icons have gone missing in 3.2?

### ISSUE THREAD

**Issue by Bang257** [bryanbrazil/skin.mimic#25]
Hello,

Recently upgraded KODI (Jarvis 16 beta 5) and correspondingly Mimic(3.2). I've noticed all my watched status icons have disappeared on shows/movies (As well as the nice default power home menu page..but that's fixable by the end user)

I DO really  like the changes made overall in the last version or two  -- especially the simplification of widgets

Thanks for any help you can provide!

**Comment by bryanbrazil** [comment]
I reconfigured all of the watched/unwatched/resumable skin settings and they are now all turned off by default. To turn them on, go to Skin Settings > General > Watched Status Indicator

**Comment by Bang257** [comment]
I see

Certainly a user-error problem, not skin problem then. Spent like an hour looking for an option saying "off" on the right-hand side..must have passed that setting a dozen or more times =)

Thank you!
