### ISSUE TITLE
EnterMasterMode not showing up in Dialog Button Menu

### ISSUE THREAD

**Issue by indritix** [bryanbrazil/skin.mimic#27]
Hi thanks for this great skin, however the "enter master mode" text doesn't show up in the when selecting "DialogButtonMenu.xml". 
I think the problem is that no "label" has been set up, therefore my question:
How do I find out which number to put in there?
I see in "DialogButtonMenu.xml" that for example "reboot" has "label 13013", and so on.
But no label for "EnterMAsterMode"... as reported below:
\<control type="togglebutton" id="10">
			\<description>Master mode button</description>
			\<texturefocus>listselect_fo.png</texturefocus>
		\<texturenofocus>-</texturenofocus>
				\<usealttexture>!System.IsMaster</usealttexture>
				\<alttexturefocus>listselect_fo.png</alttexturefocus>
				\<alttexturenofocus>-</alttexturenofocus>
				\<onclick>mastermode</onclick>
				\<font>font14</font>
				\<visible>System.HasLocks</visible>
				\<colordiffuse>$VAR[ColorHighlightVar]</colordiffuse>
			\</control>

**Comment by bryanbrazil** [comment]
Should now be fixed on github.
