### ISSUE TITLE
Menu items disappear when linking to add-ons

### ISSUE THREAD

**Issue by Tadly** [bryanbrazil/skin.mimic#29]
Eyup :)

Really liking the looks of your skin, **but** I encountered a *small* problem.

When I change a main-menu items action to point to a add-on (e.g. music to point to a add-on instead of the music-library) it disappears on the home screen while still showing within script.skinshortcuts.

Tested on Jarvis with:
* Skin version from the official kodi repo
* Master branch

If you need more input, let me know :)

**Comment by bryanbrazil** [comment]
Does this only happen with music addons? Sounds like an issue that has been discussed in the skinshortcuts thread on the Kodi forum. Try updated to the latest skinshortcuts script from github and see if that solves it.

https://github.com/BigNoid/script.skinshortcuts

**Comment by Tadly** [comment]
Updated, worked :)

Haven't had problems with skinshortcuts and refocus so I wasn't quite sure what's up

Thanks for the help ;)
