### ISSUE TITLE
Huge icons in the Settings Panel

### ISSUE THREAD

**Issue by indritix** [bryanbrazil/skin.mimic#31]
Hi, after a git pull today, I noticed the icons in the settings panel are bigger than before the update, therefore not fitting all in my TV screen. 
Is there somewhere I could change to the previous size and layout?
Tried taking a screenshot with:
`kodi-send --action="TakeScreenshot"` but didn't work, sorry.

Not really an issue but didn't know where to ask..

**Comment by bryanbrazil** [comment]
I redesigned the Settings windows to better fit the rest of the skin. No plans to change it, you would need to mod it to go back to the previous design.
