### ISSUE TITLE
Impossible to translate some items

### ISSUE THREAD

**Issue by alexandre-lg** [bryanbrazil/skin.mimic#6]
Hello,

Can you allow the translation of the following elements :
* InfoWall
* BigList
* Gallery
* Panel
* Power

Thanks a lot for your work and good luck for the next step.﻿

**Comment by bryanbrazil** [comment]
Thanks, will localize these strings in the next version.

**Comment by aruhuno** [comment]
Thank you!

Can you tell me when it is OK?

**Comment by aruhuno** [comment]
Hello,

I forgot one :
* TV SHOWS (on menu)

Thanks !

**Comment by bryanbrazil** [comment]
Is there still an issue with French strings? I pulled the updates from Transifex a couple of days ago. Just make sure Transifex is updated and I will do another pull before the next submission to the repo.

**Comment by alexandre-lg** [comment]
All is OK except "POWER" menu at the homescreen.

Thanks for your work !

**Comment by bryanbrazil** [comment]
Finally narrowed down the problem, there isn't anything wrong with the skin files. The shutdown menu item uses string #33060 from Kodi's language file as the fallback. I just looked in Kodi's French strings.po file, and it has the Power string translated as "Power." If you'd like it to be something else, you will need to update it in Kodi's main French translation file.

**Comment by alexandre-lg** [comment]
Thanks for your help!
